### ISSUE TITLE
Incorrect Azure credentials causes panic

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/cloudinfo#384]
**Describe the bug**
Incorrect Azure credentials results in a panic:

```
{"application":"cloudinfo","component":"scraping-manager","environment":"production","level":"error","msg":"failed to initialize cloud product information","provider":"azure","time":"2020-09-08T14:38:08+05:30"}
panic: runtime error: comparing uncomparable type autorest.DetailedError
```

**Steps to reproduce the issue:**
Start the scraper service with incorrect Azure credentials.

**Expected behavior**
The scraper service cannot work without valid credentials and the current practice is to exit with an error. However, the error should reflect the cause properly.

**Comment by bandesz** [comment]
@sagikazarmark thanks for opening this issue. I did some investigation and it turns out the panic is caused by the logur library's errorhandler.

Full stack trace:
```
panic: runtime error: comparing uncomparable type autorest.DetailedError

goroutine 29 [running]:
emperror.dev/handler/logur.(*Handler).Handle(0xc000300fc0, 0x376b2e0, 0xc000244460)
	/Users/andras/pkg/mod/emperror.dev/handler/logur@v0.4.0/handler.go:94 +0x464
github.com/banzaicloud/cloudinfo/internal/cloudinfo.(*scrapingManager).initialize(0xc000549d00, 0x37b4fe0, 0xc0008e8060)
	/Users/andras/src/github.com/appvia/cloudinfo/internal/cloudinfo/scrape.go:54 +0x55f
github.com/banzaicloud/cloudinfo/internal/cloudinfo.(*scrapingManager).scrape(0xc000549d00, 0x37b4fe0, 0xc0008e8060)
	/Users/andras/src/github.com/appvia/cloudinfo/internal/cloudinfo/scrape.go:303 +0x292
created by github.com/banzaicloud/cloudinfo/internal/cloudinfo.(*ScrapingDriver).renewAll
	/Users/andras/src/github.com/appvia/cloudinfo/internal/cloudinfo/scrape.go:371 +0x75
```

Relevant logur line:
```
	if errs := getErrors(err); len(errs) > 1 || errs[0] == err {
```

Any non-comparable error type will cause a panic because of this. **autorest.DetailedError** contains a []byte field, therefore non-comparable.

It seems you're the author of logur, do you think the problem is fixed in newer versions? If yes, do you have a plan to upgrade logur to an appropriate version?

**Comment by sagikazarmark** [comment]
@bandesz I don't think it's fixed yet, because I've never seen this error before. I'll take a look at it later today. Thanks for the investigation.

**Comment by sagikazarmark** [comment]
@bandesz 0.17.1 (chart: 0.8.4) should address the issue.

**Comment by bandesz** [comment]
Thank you!
